[project]
name = "nemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.5.0",
    "ftfy>=6.3.1",
    "huggingface-hub>=0.30.1",
    "polars>=1.26.0",
    "python-dotenv>=1.1.0",
    "torch>=2.6.0",
]
